name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    # Instala as dependências
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc clang gcov valgrind cppcheck

    # Make Clean e Make Gerar Arquivo
    - name: make
      run: "make clean; make"

    # CppCheck
    - name: Run cppcheck
      run: cppcheck --enable=all --inconclusive --error-exitcode=1 .



